### ISSUE TITLE
Build Failure Due to Compile Errors

### ISSUE THREAD

**Issue by abdijavad110** [marvinwilliams/multiqueue_experiments#1]
# Description:
I couldn't find build instructions in this repo and it would be really helpful to have some.

I tried to build it in a conventional manner, but I encountered a few errors. Most importantly, some files are including other files from `multiqueue` that does not exist. For example, `priority_queue_factory.hpp` imports `config.hpp` and `stick_policy.h`, which does not exist in `multiqueue`: https://github.com/marvinwilliams/multiqueue_experiments/blob/9cf91065f7899a30c1a651a59ecc491e1cafec30/util/priority_queue_factory.hpp#L16-L18

# Environment:
* Operating System: Ubuntu 22.04
* Compiler: g++ 11.3.0
* Build System: cmake 3.26.4 & GNU Make 4.3

# Steps to Reproduce:
```bash
git clone https://github.com/marvinwilliams/multiqueue_experiments
cd multiqueue_experiments
git submodule init
git submodule update

cmake --preset=release
cd build/release
make -j
```

**Comment by marvinwilliams** [comment]
this problem was due to a mismatch of the submodule commit.
